controller_list:
  - name: fake_EE_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_J1_controller
    type: $(arg fake_execution_type)
    joints:
      - J1_Motor
      - J1_Upper
  - name: fake_J2_controller
    type: $(arg fake_execution_type)
    joints:
      - J2_Motor
      - J2_Upper
  - name: fake_J3_controller
    type: $(arg fake_execution_type)
    joints:
      - J3_Motor
      - J3_Upper
  - name: fake_Base_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_Delta_controller
    type: $(arg fake_execution_type)
    joints:
      - J1_Motor
      - J1_Upper
      - J2_Motor
      - J2_Upper
      - J3_Motor
      - J3_Upper
initial:  # Define initial robot poses per group
  - group: Delta
    pose: Delta