J1:
  kinematics_solver: fanuc_kinematics::KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
J2:
  kinematics_solver: fanuc_kinematics::KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
J3:
  kinematics_solver: fanuc_kinematics::KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005