controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - J1_Motor
    - J2_Motor
    - J3_Motor
  gains:
    J1_Motor:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J2_Motor:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J3_Motor:
      p: 100
      d: 1
      i: 1
      i_clamp: 1