controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - left_finger_joint
      - right_finger_joint
initial:  # Define initial robot poses per group
  - group: M430ia
    pose: home
  - group: gripper
    pose: home