controller_list:
  - name: fake_M430ia_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger_joint
  - name: fake_ee_links_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger_joint
  - name: fake_ee_frame_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: M430ia
    pose: home
  - group: gripper
    pose: home