M430ia_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
  constraints:
    stopped_velocity_tolerance: 0
  gains:
    joint_1:
      p: 400
      d: 10
      i: 1
      i_clamp: 1
    joint_2:
      p: 400
      d: 20
      i: 2
      i_clamp: 3
    joint_3:
      p: 1000
      d: 10
      i: 1
      i_clamp: 1
    joint_4:
      p: 1000
      d: 10
      i: 1
      i_clamp: 1
    joint_5:
      p: 300
      d: 10
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_finger_joint
    - right_finger_joint
  constraints:
    stopped_velocity_tolerance: 0
  gains:
    left_finger_joint:
      p: 100
      d: 10
      i: 1
      i_clamp: 1
    right_finger_joint:
      p: 100
      d: 10
      i: 1
      i_clamp: 1