joint1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100.0, i: 1, d: 10.0}
joint2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100.0, i: 1, d: 10.0}
joint3_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100.0, i: 1, d: 10.0}
joint4_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 100.0, i: 1, d: 10.0}
joint5_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 100.0, i: 1, d: 10.0}

left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: left_finger_joint
    pid: {p: 100.0, i: 1, d: 10.0}

right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: right_finger_joint
    pid: {p: 100.0, i: 1, d: 10.0}